import type { NextPage } from 'next'
import Head from 'next/head'

const Blog: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-">
        <h1>
          Blog Pages
        </h1>
      </main>

      <footer className="">
      </footer>
    </div>
  )
}

export default Blog
